version: "2"

services:
 mysqldb:
   image: mysql:5.7
   restart: unless-stopped
   environment:
    MYSQL_DATABASE: achatdb
    MYSQL_USER: root
    MYSQL_PASSWORD: 
    MYSQL_ROOT_PASSWORD: 
   ports:
      - "3306:3306"
   volumes:
      - db:/var/lib/mysql
 app:
   container_name: spring
   image: validcards20/devops
   depends_on:
     - mysqldb
   build: .
   restart: on-failure
   ports:
     - "8089:8089"
   environment:
     SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
       "spring.datasource.username" : "root",
       "spring.datasource.password" : "",
       "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
       "spring.jpa.hibernate.ddl-auto" : "update"}'
   stdin_open: true
   tty: true
    
    
 

volumes:
 db:
